/* application.c generated by valac 0.56.3, the Vala compiler
 * generated from application.vala, do not modify */

/* application.vala
 *
 * Copyright 2022 Jose Hunter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <adwaita.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define HACER_TYPE_APPLICATION (hacer_application_get_type ())
#define HACER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HACER_TYPE_APPLICATION, HacerApplication))
#define HACER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HACER_TYPE_APPLICATION, HacerApplicationClass))
#define HACER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HACER_TYPE_APPLICATION))
#define HACER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HACER_TYPE_APPLICATION))
#define HACER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HACER_TYPE_APPLICATION, HacerApplicationClass))

typedef struct _HacerApplication HacerApplication;
typedef struct _HacerApplicationClass HacerApplicationClass;
typedef struct _HacerApplicationPrivate HacerApplicationPrivate;
enum  {
	HACER_APPLICATION_0_PROPERTY,
	HACER_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* hacer_application_properties[HACER_APPLICATION_NUM_PROPERTIES];

#define HACER_TYPE_WINDOW (hacer_window_get_type ())
#define HACER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HACER_TYPE_WINDOW, HacerWindow))
#define HACER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HACER_TYPE_WINDOW, HacerWindowClass))
#define HACER_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HACER_TYPE_WINDOW))
#define HACER_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HACER_TYPE_WINDOW))
#define HACER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HACER_TYPE_WINDOW, HacerWindowClass))

typedef struct _HacerWindow HacerWindow;
typedef struct _HacerWindowClass HacerWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _HacerApplication {
	AdwApplication parent_instance;
	HacerApplicationPrivate * priv;
};

struct _HacerApplicationClass {
	AdwApplicationClass parent_class;
};

static gpointer hacer_application_parent_class = NULL;

VALA_EXTERN GType hacer_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HacerApplication, g_object_unref)
VALA_EXTERN HacerApplication* hacer_application_new (void);
VALA_EXTERN HacerApplication* hacer_application_construct (GType object_type);
static void hacer_application_real_activate (GApplication* base);
VALA_EXTERN HacerWindow* hacer_window_new (GtkApplication* app);
VALA_EXTERN HacerWindow* hacer_window_construct (GType object_type,
                                     GtkApplication* app);
VALA_EXTERN GType hacer_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HacerWindow, g_object_unref)
static void hacer_application_on_about_action (HacerApplication* self);
static gchar** _vala_array_dup1 (gchar** self,
                          gssize length);
static void hacer_application_on_preferences_action (HacerApplication* self);
static GObject * hacer_application_constructor (GType type,
                                         guint n_construct_properties,
                                         GObjectConstructParam * construct_properties);
static void _hacer_application_on_about_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                          GVariant* parameter,
                                                                          gpointer self);
static void _hacer_application_on_preferences_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                                GVariant* parameter,
                                                                                gpointer self);
static void _g_application_quit_gsimple_action_activate_callback (GSimpleAction* action,
                                                           GVariant* parameter,
                                                           gpointer self);
static GType hacer_application_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

HacerApplication*
hacer_application_construct (GType object_type)
{
	HacerApplication * self = NULL;
#line 24 "../src/application.vala"
	self = (HacerApplication*) g_object_new (object_type, "application-id", "com.github.halfmexican.hacer", "flags", G_APPLICATION_FLAGS_NONE, NULL);
#line 23 "../src/application.vala"
	return self;
#line 124 "application.c"
}

HacerApplication*
hacer_application_new (void)
{
#line 23 "../src/application.vala"
	return hacer_application_construct (HACER_TYPE_APPLICATION);
#line 132 "application.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 39 "../src/application.vala"
	return self ? g_object_ref (self) : NULL;
#line 140 "application.c"
}

static void
hacer_application_real_activate (GApplication* base)
{
	HacerApplication * self;
	GtkWindow* win = NULL;
	GtkWindow* _tmp0_;
	GtkWindow* _tmp1_;
	GtkWindow* _tmp2_;
	GtkWindow* _tmp3_;
	GtkWindow* _tmp5_;
#line 37 "../src/application.vala"
	self = (HacerApplication*) base;
#line 38 "../src/application.vala"
	G_APPLICATION_CLASS (hacer_application_parent_class)->activate ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, adw_application_get_type (), AdwApplication));
#line 39 "../src/application.vala"
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 39 "../src/application.vala"
	_tmp1_ = _tmp0_;
#line 39 "../src/application.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 39 "../src/application.vala"
	win = _tmp2_;
#line 40 "../src/application.vala"
	_tmp3_ = win;
#line 40 "../src/application.vala"
	if (_tmp3_ == NULL) {
#line 169 "application.c"
		HacerWindow* _tmp4_;
#line 41 "../src/application.vala"
		_tmp4_ = hacer_window_new ((GtkApplication*) self);
#line 41 "../src/application.vala"
		g_object_ref_sink (_tmp4_);
#line 41 "../src/application.vala"
		_g_object_unref0 (win);
#line 41 "../src/application.vala"
		win = (GtkWindow*) _tmp4_;
#line 179 "application.c"
	}
#line 43 "../src/application.vala"
	_tmp5_ = win;
#line 43 "../src/application.vala"
	gtk_window_present (_tmp5_);
#line 37 "../src/application.vala"
	_g_object_unref0 (win);
#line 187 "application.c"
}

static gchar**
_vala_array_dup1 (gchar** self,
                  gssize length)
{
#line 48 "../src/application.vala"
	if (length >= 0) {
#line 196 "application.c"
		gchar** result;
		gssize i;
#line 48 "../src/application.vala"
		result = g_new0 (gchar*, length + 1);
#line 48 "../src/application.vala"
		for (i = 0; i < length; i++) {
#line 203 "application.c"
			gchar* _tmp0_;
#line 48 "../src/application.vala"
			_tmp0_ = g_strdup (self[i]);
#line 48 "../src/application.vala"
			result[i] = _tmp0_;
#line 209 "application.c"
		}
#line 48 "../src/application.vala"
		return result;
#line 213 "application.c"
	}
#line 48 "../src/application.vala"
	return NULL;
#line 217 "application.c"
}

static void
hacer_application_on_about_action (HacerApplication* self)
{
	gchar** developers = NULL;
	gchar* _tmp0_;
	gchar** _tmp1_;
	gint developers_length1;
	gint _developers_size_;
	AdwAboutWindow* about = NULL;
	GtkWindow* _tmp2_;
	GtkWindow* _tmp3_;
	GtkWindow* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gchar* _tmp10_;
	AdwAboutWindow* _tmp11_ = NULL;
#line 46 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 47 "../src/application.vala"
	_tmp0_ = g_strdup ("Jose Hunter");
#line 47 "../src/application.vala"
	_tmp1_ = g_new0 (gchar*, 1 + 1);
#line 47 "../src/application.vala"
	_tmp1_[0] = _tmp0_;
#line 47 "../src/application.vala"
	developers = _tmp1_;
#line 47 "../src/application.vala"
	developers_length1 = 1;
#line 47 "../src/application.vala"
	_developers_size_ = developers_length1;
#line 48 "../src/application.vala"
	_tmp2_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 48 "../src/application.vala"
	_tmp3_ = _tmp2_;
#line 48 "../src/application.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 48 "../src/application.vala"
	_tmp5_ = g_strdup ("hacer");
#line 48 "../src/application.vala"
	_tmp6_ = g_strdup ("com.github.halfmexican.hacer");
#line 48 "../src/application.vala"
	_tmp7_ = g_strdup ("Jose Hunter");
#line 48 "../src/application.vala"
	_tmp8_ = g_strdup ("0.1.0");
#line 48 "../src/application.vala"
	_tmp9_ = (developers != NULL) ? _vala_array_dup1 (developers, developers_length1) : developers;
#line 48 "../src/application.vala"
	_tmp9__length1 = developers_length1;
#line 48 "../src/application.vala"
	_tmp10_ = g_strdup ("© 2022 Jose Hunter");
#line 48 "../src/application.vala"
	_tmp11_ = (AdwAboutWindow*) adw_about_window_new ();
#line 48 "../src/application.vala"
	gtk_window_set_transient_for ((GtkWindow*) _tmp11_, _tmp4_);
#line 48 "../src/application.vala"
	_g_object_unref0 (_tmp4_);
#line 48 "../src/application.vala"
	adw_about_window_set_application_name (_tmp11_, _tmp5_);
#line 48 "../src/application.vala"
	_g_free0 (_tmp5_);
#line 48 "../src/application.vala"
	adw_about_window_set_application_icon (_tmp11_, _tmp6_);
#line 48 "../src/application.vala"
	_g_free0 (_tmp6_);
#line 48 "../src/application.vala"
	adw_about_window_set_developer_name (_tmp11_, _tmp7_);
#line 48 "../src/application.vala"
	_g_free0 (_tmp7_);
#line 48 "../src/application.vala"
	adw_about_window_set_version (_tmp11_, _tmp8_);
#line 48 "../src/application.vala"
	_g_free0 (_tmp8_);
#line 48 "../src/application.vala"
	adw_about_window_set_developers (_tmp11_, _tmp9_);
#line 48 "../src/application.vala"
	_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
#line 48 "../src/application.vala"
	adw_about_window_set_copyright (_tmp11_, _tmp10_);
#line 48 "../src/application.vala"
	_g_free0 (_tmp10_);
#line 48 "../src/application.vala"
	g_object_ref_sink (_tmp11_);
#line 48 "../src/application.vala"
	about = _tmp11_;
#line 58 "../src/application.vala"
	gtk_window_present ((GtkWindow*) about);
#line 46 "../src/application.vala"
	_g_object_unref0 (about);
#line 46 "../src/application.vala"
	developers = (_vala_array_free (developers, developers_length1, (GDestroyNotify) g_free), NULL);
#line 314 "application.c"
}

static void
hacer_application_on_preferences_action (HacerApplication* self)
{
#line 61 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 62 "../src/application.vala"
	g_message ("application.vala:62: app.preferences action activated");
#line 324 "application.c"
}

static void
_hacer_application_on_about_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                     GVariant* parameter,
                                                                     gpointer self)
{
#line 28 "../src/application.vala"
	hacer_application_on_about_action ((HacerApplication*) self);
#line 334 "application.c"
}

static void
_hacer_application_on_preferences_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                           GVariant* parameter,
                                                                           gpointer self)
{
#line 28 "../src/application.vala"
	hacer_application_on_preferences_action ((HacerApplication*) self);
#line 344 "application.c"
}

static void
_g_application_quit_gsimple_action_activate_callback (GSimpleAction* action,
                                                      GVariant* parameter,
                                                      gpointer self)
{
#line 28 "../src/application.vala"
	g_application_quit ((GApplication*) self);
#line 354 "application.c"
}

static GObject *
hacer_application_constructor (GType type,
                               guint n_construct_properties,
                               GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	HacerApplication * self;
	GActionEntry* action_entries = NULL;
	GActionEntry _tmp0_ = {0};
	GActionEntry _tmp1_ = {0};
	GActionEntry _tmp2_ = {0};
	GActionEntry* _tmp3_;
	gint action_entries_length1;
	gint _action_entries_size_;
	GActionEntry* _tmp4_;
	gint _tmp4__length1;
	gchar* _tmp5_;
	gchar** _tmp6_;
	gchar** _tmp7_;
	gint _tmp7__length1;
#line 27 "../src/application.vala"
	parent_class = G_OBJECT_CLASS (hacer_application_parent_class);
#line 27 "../src/application.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 27 "../src/application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HACER_TYPE_APPLICATION, HacerApplication);
#line 28 "../src/application.vala"
	memset (&_tmp0_, 0, sizeof (GActionEntry));
#line 28 "../src/application.vala"
	_tmp0_.name = "about";
#line 28 "../src/application.vala"
	_tmp0_.activate = _hacer_application_on_about_action_gsimple_action_activate_callback;
#line 28 "../src/application.vala"
	memset (&_tmp1_, 0, sizeof (GActionEntry));
#line 28 "../src/application.vala"
	_tmp1_.name = "preferences";
#line 28 "../src/application.vala"
	_tmp1_.activate = _hacer_application_on_preferences_action_gsimple_action_activate_callback;
#line 28 "../src/application.vala"
	memset (&_tmp2_, 0, sizeof (GActionEntry));
#line 28 "../src/application.vala"
	_tmp2_.name = "quit";
#line 28 "../src/application.vala"
	_tmp2_.activate = _g_application_quit_gsimple_action_activate_callback;
#line 28 "../src/application.vala"
	_tmp3_ = g_new0 (GActionEntry, 3);
#line 28 "../src/application.vala"
	_tmp3_[0] = _tmp0_;
#line 28 "../src/application.vala"
	_tmp3_[1] = _tmp1_;
#line 28 "../src/application.vala"
	_tmp3_[2] = _tmp2_;
#line 28 "../src/application.vala"
	action_entries = _tmp3_;
#line 28 "../src/application.vala"
	action_entries_length1 = 3;
#line 28 "../src/application.vala"
	_action_entries_size_ = action_entries_length1;
#line 33 "../src/application.vala"
	_tmp4_ = action_entries;
#line 33 "../src/application.vala"
	_tmp4__length1 = action_entries_length1;
#line 33 "../src/application.vala"
	g_action_map_add_action_entries ((GActionMap*) self, _tmp4_, (gint) _tmp4__length1, self);
#line 34 "../src/application.vala"
	_tmp5_ = g_strdup ("<primary>q");
#line 34 "../src/application.vala"
	_tmp6_ = g_new0 (gchar*, 1 + 1);
#line 34 "../src/application.vala"
	_tmp6_[0] = _tmp5_;
#line 34 "../src/application.vala"
	_tmp7_ = _tmp6_;
#line 34 "../src/application.vala"
	_tmp7__length1 = 1;
#line 34 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.quit", _tmp7_);
#line 34 "../src/application.vala"
	_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) g_free), NULL);
#line 27 "../src/application.vala"
	action_entries = (g_free (action_entries), NULL);
#line 27 "../src/application.vala"
	return obj;
#line 440 "application.c"
}

static void
hacer_application_class_init (HacerApplicationClass * klass,
                              gpointer klass_data)
{
#line 22 "../src/application.vala"
	hacer_application_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/application.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) hacer_application_real_activate;
#line 22 "../src/application.vala"
	G_OBJECT_CLASS (klass)->constructor = hacer_application_constructor;
#line 453 "application.c"
}

static void
hacer_application_instance_init (HacerApplication * self,
                                 gpointer klass)
{
}

static GType
hacer_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (HacerApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hacer_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HacerApplication), 0, (GInstanceInitFunc) hacer_application_instance_init, NULL };
	GType hacer_application_type_id;
	hacer_application_type_id = g_type_register_static (adw_application_get_type (), "HacerApplication", &g_define_type_info, 0);
	return hacer_application_type_id;
}

GType
hacer_application_get_type (void)
{
	static volatile gsize hacer_application_type_id__once = 0;
	if (g_once_init_enter (&hacer_application_type_id__once)) {
		GType hacer_application_type_id;
		hacer_application_type_id = hacer_application_get_type_once ();
		g_once_init_leave (&hacer_application_type_id__once, hacer_application_type_id);
	}
	return hacer_application_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

