/* main.c generated by valac 0.56.3, the Vala compiler
 * generated from main.vala, do not modify */

/* main.vala
 *
 * Copyright 2022 Jose Hunter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <adwaita.h>
#include <glib-object.h>
#include <gio/gio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define HACER_TYPE_APPLICATION (hacer_application_get_type ())
#define HACER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HACER_TYPE_APPLICATION, HacerApplication))
#define HACER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HACER_TYPE_APPLICATION, HacerApplicationClass))
#define HACER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HACER_TYPE_APPLICATION))
#define HACER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HACER_TYPE_APPLICATION))
#define HACER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HACER_TYPE_APPLICATION, HacerApplicationClass))

typedef struct _HacerApplication HacerApplication;
typedef struct _HacerApplicationClass HacerApplicationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

static gint _vala_main (gchar** args,
                 gint args_length1);
VALA_EXTERN GType hacer_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HacerApplication, g_object_unref)
VALA_EXTERN HacerApplication* hacer_application_new (void);
VALA_EXTERN HacerApplication* hacer_application_construct (GType object_type);

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	HacerApplication* app = NULL;
	HacerApplication* _tmp0_;
	gint result;
#line 22 "../src/main.vala"
	_tmp0_ = hacer_application_new ();
#line 22 "../src/main.vala"
	app = _tmp0_;
#line 23 "../src/main.vala"
	result = g_application_run ((GApplication*) app, (gint) args_length1, args);
#line 23 "../src/main.vala"
	_g_object_unref0 (app);
#line 23 "../src/main.vala"
	return result;
#line 77 "main.c"
}

int
main (int argc,
      char ** argv)
{
#line 21 "../src/main.vala"
	return _vala_main (argv, argc);
#line 86 "main.c"
}

