/* window.c generated by valac 0.56.3, the Vala compiler
 * generated from window.vala, do not modify */

/* window.vala
 *
 * Copyright 2022 Jose Hunter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <json-glib/json-glib.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define HACER_TYPE_WINDOW (hacer_window_get_type ())
#define HACER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HACER_TYPE_WINDOW, HacerWindow))
#define HACER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HACER_TYPE_WINDOW, HacerWindowClass))
#define HACER_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HACER_TYPE_WINDOW))
#define HACER_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HACER_TYPE_WINDOW))
#define HACER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HACER_TYPE_WINDOW, HacerWindowClass))

typedef struct _HacerWindow HacerWindow;
typedef struct _HacerWindowClass HacerWindowClass;
typedef struct _HacerWindowPrivate HacerWindowPrivate;
enum  {
	HACER_WINDOW_0_PROPERTY,
	HACER_WINDOW_NUM_PROPERTIES
};
static GParamSpec* hacer_window_properties[HACER_WINDOW_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define HACER_TYPE_ACTION_AGENDA_ROW (hacer_action_agenda_row_get_type ())
#define HACER_ACTION_AGENDA_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HACER_TYPE_ACTION_AGENDA_ROW, HacerActionAgendaRow))
#define HACER_ACTION_AGENDA_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HACER_TYPE_ACTION_AGENDA_ROW, HacerActionAgendaRowClass))
#define HACER_IS_ACTION_AGENDA_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HACER_TYPE_ACTION_AGENDA_ROW))
#define HACER_IS_ACTION_AGENDA_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HACER_TYPE_ACTION_AGENDA_ROW))
#define HACER_ACTION_AGENDA_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HACER_TYPE_ACTION_AGENDA_ROW, HacerActionAgendaRowClass))

typedef struct _HacerActionAgendaRow HacerActionAgendaRow;
typedef struct _HacerActionAgendaRowClass HacerActionAgendaRowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _HacerWindow {
	AdwApplicationWindow parent_instance;
	HacerWindowPrivate * priv;
};

struct _HacerWindowClass {
	AdwApplicationWindowClass parent_class;
};

struct _HacerWindowPrivate {
	GtkEntry* task_entry;
	GtkListBox* task_list;
	GtkButton* leaflet_forward;
	GtkButton* leaflet_back;
	GtkBox* task_view;
	GtkBox* list_view;
	GtkListBox* list_box_list;
	AdwLeaflet* adw_leaflet;
	AdwActionRow* all_tasks_row;
};

static gint HacerWindow_private_offset;
static gpointer hacer_window_parent_class = NULL;

VALA_EXTERN GType hacer_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HacerWindow, g_object_unref)
VALA_EXTERN HacerWindow* hacer_window_new (GtkApplication* app);
VALA_EXTERN HacerWindow* hacer_window_construct (GType object_type,
                                     GtkApplication* app);
VALA_EXTERN void hacer_window_on_enter_released (HacerWindow* self);
static void _hacer_window_on_enter_released_gtk_entry_activate (GtkEntry* _sender,
                                                         gpointer self);
VALA_EXTERN void hacer_window_show_task_view (HacerWindow* self);
static void _hacer_window_show_task_view_gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self);
VALA_EXTERN void hacer_window_show_list_view (HacerWindow* self);
static void _hacer_window_show_list_view_gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self);
VALA_EXTERN void hacer_window_show_all_tasks (HacerWindow* self);
static void _hacer_window_show_all_tasks_adw_action_row_activated (AdwActionRow* _sender,
                                                            gpointer self);
static void _hacer_window_load_task_from_json (HacerWindow* self);
static void _hacer_window_entry_add (HacerWindow* self,
                              const gchar* task_name);
VALA_EXTERN GType hacer_action_agenda_row_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HacerActionAgendaRow, g_object_unref)
VALA_EXTERN HacerActionAgendaRow* hacer_action_agenda_row_new (const gchar* task_name,
                                                   gboolean completed,
                                                   gboolean starred,
                                                   GtkListBox* parent_list_box);
VALA_EXTERN HacerActionAgendaRow* hacer_action_agenda_row_construct (GType object_type,
                                                         const gchar* task_name,
                                                         gboolean completed,
                                                         gboolean starred,
                                                         GtkListBox* parent_list_box);
VALA_EXTERN void hacer_window_add_task (HacerWindow* self,
                            const gchar* task_name,
                            gboolean complete,
                            gboolean starred);
static void _vala_JsonNode_free (JsonNode* self);
static void hacer_window_finalize (GObject * obj);
static GType hacer_window_get_type_once (void);

static inline gpointer
hacer_window_get_instance_private (HacerWindow* self)
{
	return G_STRUCT_MEMBER_P (self, HacerWindow_private_offset);
}

static void
_hacer_window_on_enter_released_gtk_entry_activate (GtkEntry* _sender,
                                                    gpointer self)
{
#line 42 "../src/window.vala"
	hacer_window_on_enter_released ((HacerWindow*) self);
#line 151 "window.c"
}

static void
_hacer_window_show_task_view_gtk_button_clicked (GtkButton* _sender,
                                                 gpointer self)
{
#line 43 "../src/window.vala"
	hacer_window_show_task_view ((HacerWindow*) self);
#line 160 "window.c"
}

static void
_hacer_window_show_list_view_gtk_button_clicked (GtkButton* _sender,
                                                 gpointer self)
{
#line 44 "../src/window.vala"
	hacer_window_show_list_view ((HacerWindow*) self);
#line 169 "window.c"
}

static void
_hacer_window_show_all_tasks_adw_action_row_activated (AdwActionRow* _sender,
                                                       gpointer self)
{
#line 45 "../src/window.vala"
	hacer_window_show_all_tasks ((HacerWindow*) self);
#line 178 "window.c"
}

HacerWindow*
hacer_window_construct (GType object_type,
                        GtkApplication* app)
{
	HacerWindow * self = NULL;
	GtkEntry* _tmp0_;
	GtkButton* _tmp1_;
	GtkButton* _tmp2_;
	AdwActionRow* _tmp3_;
	AdwLeaflet* _tmp4_;
	GtkBox* _tmp5_;
	GtkListBox* _tmp6_;
	GtkListBox* _tmp7_;
	GtkListBoxRow* _tmp8_;
#line 39 "../src/window.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 40 "../src/window.vala"
	self = (HacerWindow*) g_object_new (object_type, "application", app, NULL);
#line 42 "../src/window.vala"
	_tmp0_ = self->priv->task_entry;
#line 42 "../src/window.vala"
	g_signal_connect_object (_tmp0_, "activate", (GCallback) _hacer_window_on_enter_released_gtk_entry_activate, self, 0);
#line 43 "../src/window.vala"
	_tmp1_ = self->priv->leaflet_forward;
#line 43 "../src/window.vala"
	g_signal_connect_object (_tmp1_, "clicked", (GCallback) _hacer_window_show_task_view_gtk_button_clicked, self, 0);
#line 44 "../src/window.vala"
	_tmp2_ = self->priv->leaflet_back;
#line 44 "../src/window.vala"
	g_signal_connect_object (_tmp2_, "clicked", (GCallback) _hacer_window_show_list_view_gtk_button_clicked, self, 0);
#line 45 "../src/window.vala"
	_tmp3_ = self->priv->all_tasks_row;
#line 45 "../src/window.vala"
	g_signal_connect_object (_tmp3_, "activated", (GCallback) _hacer_window_show_all_tasks_adw_action_row_activated, self, 0);
#line 48 "../src/window.vala"
	_tmp4_ = self->priv->adw_leaflet;
#line 48 "../src/window.vala"
	_tmp5_ = self->priv->task_view;
#line 48 "../src/window.vala"
	adw_leaflet_set_visible_child (_tmp4_, (GtkWidget*) _tmp5_);
#line 50 "../src/window.vala"
	_tmp6_ = self->priv->list_box_list;
#line 50 "../src/window.vala"
	_tmp7_ = self->priv->list_box_list;
#line 50 "../src/window.vala"
	_tmp8_ = gtk_list_box_get_row_at_index (_tmp7_, 0);
#line 50 "../src/window.vala"
	gtk_list_box_select_row (_tmp6_, _tmp8_);
#line 51 "../src/window.vala"
	_hacer_window_load_task_from_json (self);
#line 39 "../src/window.vala"
	return self;
#line 233 "window.c"
}

HacerWindow*
hacer_window_new (GtkApplication* app)
{
#line 39 "../src/window.vala"
	return hacer_window_construct (HACER_TYPE_WINDOW, app);
#line 241 "window.c"
}

void
hacer_window_on_enter_released (HacerWindow* self)
{
	gchar* text = NULL;
	GtkEntry* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
#line 54 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 55 "../src/window.vala"
	_tmp0_ = self->priv->task_entry;
#line 55 "../src/window.vala"
	_tmp1_ = gtk_editable_get_text ((GtkEditable*) _tmp0_);
#line 55 "../src/window.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 55 "../src/window.vala"
	text = _tmp2_;
#line 56 "../src/window.vala"
	_hacer_window_entry_add (self, text);
#line 54 "../src/window.vala"
	_g_free0 (text);
#line 265 "window.c"
}

void
hacer_window_show_task_view (HacerWindow* self)
{
	AdwLeaflet* _tmp0_;
	GtkBox* _tmp1_;
#line 59 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 60 "../src/window.vala"
	_tmp0_ = self->priv->adw_leaflet;
#line 60 "../src/window.vala"
	_tmp1_ = self->priv->task_view;
#line 60 "../src/window.vala"
	adw_leaflet_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 281 "window.c"
}

void
hacer_window_show_list_view (HacerWindow* self)
{
	AdwLeaflet* _tmp0_;
	GtkBox* _tmp1_;
#line 63 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 64 "../src/window.vala"
	_tmp0_ = self->priv->adw_leaflet;
#line 64 "../src/window.vala"
	_tmp1_ = self->priv->list_view;
#line 64 "../src/window.vala"
	adw_leaflet_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 297 "window.c"
}

static void
_hacer_window_entry_add (HacerWindow* self,
                         const gchar* task_name)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	HacerActionAgendaRow* agenda_row = NULL;
	GtkListBox* _tmp4_;
	HacerActionAgendaRow* _tmp5_;
	GtkListBox* _tmp6_;
	GtkEntry* _tmp7_;
#line 67 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 67 "../src/window.vala"
	g_return_if_fail (task_name != NULL);
#line 68 "../src/window.vala"
	_tmp0_ = g_strconcat ("New Task: ", task_name, NULL);
#line 68 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 68 "../src/window.vala"
	_tmp2_ = g_strconcat (_tmp1_, "\n", NULL);
#line 68 "../src/window.vala"
	_tmp3_ = _tmp2_;
#line 68 "../src/window.vala"
	g_print ("%s", _tmp3_);
#line 68 "../src/window.vala"
	_g_free0 (_tmp3_);
#line 68 "../src/window.vala"
	_g_free0 (_tmp1_);
#line 69 "../src/window.vala"
	_tmp4_ = self->priv->task_list;
#line 69 "../src/window.vala"
	_tmp5_ = hacer_action_agenda_row_new (task_name, FALSE, FALSE, _tmp4_);
#line 69 "../src/window.vala"
	g_object_ref_sink (_tmp5_);
#line 69 "../src/window.vala"
	agenda_row = _tmp5_;
#line 70 "../src/window.vala"
	_tmp6_ = self->priv->task_list;
#line 70 "../src/window.vala"
	gtk_list_box_append (_tmp6_, (GtkWidget*) agenda_row);
#line 71 "../src/window.vala"
	_tmp7_ = self->priv->task_entry;
#line 71 "../src/window.vala"
	gtk_editable_set_text ((GtkEditable*) _tmp7_, "");
#line 72 "../src/window.vala"
	hacer_window_add_task (self, task_name, FALSE, FALSE);
#line 67 "../src/window.vala"
	_g_object_unref0 (agenda_row);
#line 351 "window.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 82 "../src/window.vala"
	return self ? g_object_ref (self) : NULL;
#line 359 "window.c"
}

static gpointer
_json_object_ref0 (gpointer self)
{
#line 99 "../src/window.vala"
	return self ? json_object_ref (self) : NULL;
#line 367 "window.c"
}

static void
_vala_JsonNode_free (JsonNode* self)
{
#line 99 "../src/window.vala"
	g_boxed_free (json_node_get_type (), self);
#line 375 "window.c"
}

static gpointer
_json_array_ref0 (gpointer self)
{
#line 108 "../src/window.vala"
	return self ? json_array_ref (self) : NULL;
#line 383 "window.c"
}

void
hacer_window_add_task (HacerWindow* self,
                       const gchar* task_name,
                       gboolean complete,
                       gboolean starred)
{
	GError* _inner_error0_ = NULL;
#line 75 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 75 "../src/window.vala"
	g_return_if_fail (task_name != NULL);
#line 397 "window.c"
	{
		GFile* file = NULL;
		const gchar* _tmp0_;
		gchar* _tmp1_;
		gchar* _tmp2_;
		GFile* _tmp3_;
		GFile* _tmp4_;
		GFileIOStream* iostream = NULL;
		GFile* _tmp5_;
		GFileIOStream* _tmp6_;
		GOutputStream* o_stream = NULL;
		GFileIOStream* _tmp7_;
		GOutputStream* _tmp8_;
		GOutputStream* _tmp9_;
		GOutputStream* _tmp10_;
		GDataOutputStream* do_stream = NULL;
		GOutputStream* _tmp11_;
		GDataOutputStream* _tmp12_;
		JsonBuilder* builder = NULL;
		JsonBuilder* _tmp13_;
		JsonBuilder* _tmp14_;
		JsonBuilder* _tmp21_;
		JsonObject* task_obj = NULL;
		JsonBuilder* _tmp22_;
		JsonNode* _tmp23_;
		JsonNode* _tmp24_;
		JsonObject* _tmp25_;
		JsonObject* _tmp26_;
		JsonObject* _tmp27_;
		JsonGenerator* generator = NULL;
		JsonGenerator* _tmp28_ = NULL;
		JsonParser* parser = NULL;
		JsonParser* _tmp29_;
		JsonParser* _tmp30_;
		const gchar* _tmp31_;
		gchar* _tmp32_;
		gchar* _tmp33_;
		JsonArray* array = NULL;
		JsonParser* _tmp34_;
		JsonNode* _tmp35_;
		JsonObject* _tmp36_;
		JsonArray* _tmp37_;
		JsonArray* _tmp38_;
		JsonArray* _tmp39_;
		JsonObject* _tmp40_;
		JsonObject* _tmp41_;
		JsonGenerator* _tmp42_;
		JsonParser* _tmp43_;
		JsonNode* _tmp44_;
		gchar* str = NULL;
		JsonGenerator* _tmp45_;
		gchar* _tmp46_;
		GDataOutputStream* _tmp47_;
		const gchar* _tmp48_;
#line 78 "../src/window.vala"
		_tmp0_ = g_get_user_data_dir ();
#line 78 "../src/window.vala"
		_tmp1_ = g_strconcat (_tmp0_, "/tasks.json", NULL);
#line 78 "../src/window.vala"
		_tmp2_ = _tmp1_;
#line 78 "../src/window.vala"
		_tmp3_ = g_file_new_for_path (_tmp2_);
#line 78 "../src/window.vala"
		_tmp4_ = _tmp3_;
#line 78 "../src/window.vala"
		_g_free0 (_tmp2_);
#line 78 "../src/window.vala"
		file = _tmp4_;
#line 81 "../src/window.vala"
		_tmp5_ = file;
#line 81 "../src/window.vala"
		_tmp6_ = g_file_open_readwrite (_tmp5_, NULL, &_inner_error0_);
#line 81 "../src/window.vala"
		iostream = _tmp6_;
#line 81 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 81 "../src/window.vala"
			_g_object_unref0 (file);
#line 476 "window.c"
			goto __catch0_g_error;
		}
#line 82 "../src/window.vala"
		_tmp7_ = iostream;
#line 82 "../src/window.vala"
		_tmp8_ = g_io_stream_get_output_stream ((GIOStream*) _tmp7_);
#line 82 "../src/window.vala"
		_tmp9_ = _tmp8_;
#line 82 "../src/window.vala"
		_tmp10_ = _g_object_ref0 (_tmp9_);
#line 82 "../src/window.vala"
		o_stream = _tmp10_;
#line 83 "../src/window.vala"
		_tmp11_ = o_stream;
#line 83 "../src/window.vala"
		_tmp12_ = g_data_output_stream_new (_tmp11_);
#line 83 "../src/window.vala"
		do_stream = _tmp12_;
#line 86 "../src/window.vala"
		_tmp13_ = json_builder_new ();
#line 86 "../src/window.vala"
		builder = _tmp13_;
#line 87 "../src/window.vala"
		_tmp14_ = builder;
#line 87 "../src/window.vala"
		json_builder_begin_object (_tmp14_);
#line 503 "window.c"
		{
			JsonBuilder* _tmp15_;
			JsonBuilder* _tmp16_;
			JsonBuilder* _tmp17_;
			JsonBuilder* _tmp18_;
			JsonBuilder* _tmp19_;
			JsonBuilder* _tmp20_;
#line 89 "../src/window.vala"
			_tmp15_ = builder;
#line 89 "../src/window.vala"
			json_builder_set_member_name (_tmp15_, "task_name");
#line 90 "../src/window.vala"
			_tmp16_ = builder;
#line 90 "../src/window.vala"
			json_builder_add_string_value (_tmp16_, task_name);
#line 91 "../src/window.vala"
			_tmp17_ = builder;
#line 91 "../src/window.vala"
			json_builder_set_member_name (_tmp17_, "complete");
#line 92 "../src/window.vala"
			_tmp18_ = builder;
#line 92 "../src/window.vala"
			json_builder_add_boolean_value (_tmp18_, complete);
#line 93 "../src/window.vala"
			_tmp19_ = builder;
#line 93 "../src/window.vala"
			json_builder_set_member_name (_tmp19_, "starred");
#line 94 "../src/window.vala"
			_tmp20_ = builder;
#line 94 "../src/window.vala"
			json_builder_add_boolean_value (_tmp20_, starred);
#line 535 "window.c"
		}
#line 96 "../src/window.vala"
		_tmp21_ = builder;
#line 96 "../src/window.vala"
		json_builder_end_object (_tmp21_);
#line 99 "../src/window.vala"
		_tmp22_ = builder;
#line 99 "../src/window.vala"
		_tmp23_ = json_builder_get_root (_tmp22_);
#line 99 "../src/window.vala"
		_tmp24_ = _tmp23_;
#line 99 "../src/window.vala"
		_tmp25_ = json_node_get_object (_tmp24_);
#line 99 "../src/window.vala"
		_tmp26_ = _json_object_ref0 (_tmp25_);
#line 99 "../src/window.vala"
		_tmp27_ = _tmp26_;
#line 99 "../src/window.vala"
		__vala_JsonNode_free0 (_tmp24_);
#line 99 "../src/window.vala"
		task_obj = _tmp27_;
#line 103 "../src/window.vala"
		_tmp28_ = json_generator_new ();
#line 103 "../src/window.vala"
		json_generator_set_pretty (_tmp28_, TRUE);
#line 103 "../src/window.vala"
		generator = _tmp28_;
#line 104 "../src/window.vala"
		_tmp29_ = json_parser_new ();
#line 104 "../src/window.vala"
		parser = _tmp29_;
#line 107 "../src/window.vala"
		_tmp30_ = parser;
#line 107 "../src/window.vala"
		_tmp31_ = g_get_user_data_dir ();
#line 107 "../src/window.vala"
		_tmp32_ = g_strconcat (_tmp31_, "/tasks.json", NULL);
#line 107 "../src/window.vala"
		_tmp33_ = _tmp32_;
#line 107 "../src/window.vala"
		json_parser_load_from_file (_tmp30_, _tmp33_, &_inner_error0_);
#line 107 "../src/window.vala"
		_g_free0 (_tmp33_);
#line 107 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 107 "../src/window.vala"
			_g_object_unref0 (parser);
#line 107 "../src/window.vala"
			_g_object_unref0 (generator);
#line 107 "../src/window.vala"
			_json_object_unref0 (task_obj);
#line 107 "../src/window.vala"
			_g_object_unref0 (builder);
#line 107 "../src/window.vala"
			_g_object_unref0 (do_stream);
#line 107 "../src/window.vala"
			_g_object_unref0 (o_stream);
#line 107 "../src/window.vala"
			_g_object_unref0 (iostream);
#line 107 "../src/window.vala"
			_g_object_unref0 (file);
#line 597 "window.c"
			goto __catch0_g_error;
		}
#line 108 "../src/window.vala"
		_tmp34_ = parser;
#line 108 "../src/window.vala"
		_tmp35_ = json_parser_get_root (_tmp34_);
#line 108 "../src/window.vala"
		_tmp36_ = json_node_get_object (_tmp35_);
#line 108 "../src/window.vala"
		_tmp37_ = json_object_get_array_member (_tmp36_, "Tasks");
#line 108 "../src/window.vala"
		_tmp38_ = _json_array_ref0 (_tmp37_);
#line 108 "../src/window.vala"
		array = _tmp38_;
#line 109 "../src/window.vala"
		_tmp39_ = array;
#line 109 "../src/window.vala"
		_tmp40_ = task_obj;
#line 109 "../src/window.vala"
		_tmp41_ = _json_object_ref0 (_tmp40_);
#line 109 "../src/window.vala"
		json_array_add_object_element (_tmp39_, _tmp41_);
#line 112 "../src/window.vala"
		_tmp42_ = generator;
#line 112 "../src/window.vala"
		_tmp43_ = parser;
#line 112 "../src/window.vala"
		_tmp44_ = json_parser_get_root (_tmp43_);
#line 112 "../src/window.vala"
		json_generator_set_root (_tmp42_, _tmp44_);
#line 113 "../src/window.vala"
		_tmp45_ = generator;
#line 113 "../src/window.vala"
		_tmp46_ = json_generator_to_data (_tmp45_, NULL);
#line 113 "../src/window.vala"
		str = _tmp46_;
#line 114 "../src/window.vala"
		_tmp47_ = do_stream;
#line 114 "../src/window.vala"
		_tmp48_ = str;
#line 114 "../src/window.vala"
		g_data_output_stream_put_string (_tmp47_, _tmp48_, NULL, &_inner_error0_);
#line 114 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 114 "../src/window.vala"
			_g_free0 (str);
#line 114 "../src/window.vala"
			_json_array_unref0 (array);
#line 114 "../src/window.vala"
			_g_object_unref0 (parser);
#line 114 "../src/window.vala"
			_g_object_unref0 (generator);
#line 114 "../src/window.vala"
			_json_object_unref0 (task_obj);
#line 114 "../src/window.vala"
			_g_object_unref0 (builder);
#line 114 "../src/window.vala"
			_g_object_unref0 (do_stream);
#line 114 "../src/window.vala"
			_g_object_unref0 (o_stream);
#line 114 "../src/window.vala"
			_g_object_unref0 (iostream);
#line 114 "../src/window.vala"
			_g_object_unref0 (file);
#line 662 "window.c"
			goto __catch0_g_error;
		}
#line 76 "../src/window.vala"
		_g_free0 (str);
#line 76 "../src/window.vala"
		_json_array_unref0 (array);
#line 76 "../src/window.vala"
		_g_object_unref0 (parser);
#line 76 "../src/window.vala"
		_g_object_unref0 (generator);
#line 76 "../src/window.vala"
		_json_object_unref0 (task_obj);
#line 76 "../src/window.vala"
		_g_object_unref0 (builder);
#line 76 "../src/window.vala"
		_g_object_unref0 (do_stream);
#line 76 "../src/window.vala"
		_g_object_unref0 (o_stream);
#line 76 "../src/window.vala"
		_g_object_unref0 (iostream);
#line 76 "../src/window.vala"
		_g_object_unref0 (file);
#line 685 "window.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp49_;
		const gchar* _tmp50_;
#line 76 "../src/window.vala"
		e = _inner_error0_;
#line 76 "../src/window.vala"
		_inner_error0_ = NULL;
#line 117 "../src/window.vala"
		_tmp49_ = e;
#line 117 "../src/window.vala"
		_tmp50_ = _tmp49_->message;
#line 117 "../src/window.vala"
		g_print ("%s", _tmp50_);
#line 76 "../src/window.vala"
		_g_error_free0 (e);
#line 705 "window.c"
	}
	__finally0:
#line 76 "../src/window.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 76 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 76 "../src/window.vala"
		g_clear_error (&_inner_error0_);
#line 76 "../src/window.vala"
		return;
#line 716 "window.c"
	}
}

void
hacer_window_show_all_tasks (HacerWindow* self)
{
#line 121 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 725 "window.c"
}

static void
_hacer_window_load_task_from_json (HacerWindow* self)
{
	const gchar* task_name = NULL;
	gboolean complete = FALSE;
	gboolean starred = FALSE;
	GFile* file = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GFile* _tmp3_;
	GFile* _tmp4_;
	GFile* _tmp5_;
	JsonParser* parser = NULL;
	JsonParser* _tmp14_;
	JsonParser* _tmp15_;
	GFile* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	JsonObject* root_object = NULL;
	JsonParser* _tmp19_;
	JsonNode* _tmp20_;
	JsonObject* _tmp21_;
	JsonObject* _tmp22_;
	JsonArray* array = NULL;
	JsonObject* _tmp23_;
	JsonArray* _tmp24_;
	JsonArray* _tmp25_;
	JsonArray* _tmp26_;
	GList* _tmp27_;
	GError* _inner_error0_ = NULL;
#line 125 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 126 "../src/window.vala"
	task_name = NULL;
#line 127 "../src/window.vala"
	complete = FALSE;
#line 128 "../src/window.vala"
	starred = FALSE;
#line 131 "../src/window.vala"
	_tmp0_ = g_get_user_data_dir ();
#line 131 "../src/window.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/tasks.json", NULL);
#line 131 "../src/window.vala"
	_tmp2_ = _tmp1_;
#line 131 "../src/window.vala"
	_tmp3_ = g_file_new_for_path (_tmp2_);
#line 131 "../src/window.vala"
	_tmp4_ = _tmp3_;
#line 131 "../src/window.vala"
	_g_free0 (_tmp2_);
#line 131 "../src/window.vala"
	file = _tmp4_;
#line 133 "../src/window.vala"
	_tmp5_ = file;
#line 133 "../src/window.vala"
	if (!g_file_query_exists (_tmp5_, NULL)) {
#line 785 "window.c"
		GFile* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		GFileOutputStream* file_stream = NULL;
		GFile* _tmp9_;
		GFileOutputStream* _tmp10_;
#line 134 "../src/window.vala"
		_tmp6_ = file;
#line 134 "../src/window.vala"
		_tmp7_ = g_file_get_path (_tmp6_);
#line 134 "../src/window.vala"
		_tmp8_ = _tmp7_;
#line 134 "../src/window.vala"
		g_print ("File '%s' does not exist.", _tmp8_);
#line 134 "../src/window.vala"
		_g_free0 (_tmp8_);
#line 136 "../src/window.vala"
		_tmp9_ = file;
#line 136 "../src/window.vala"
		_tmp10_ = g_file_create (_tmp9_, G_FILE_CREATE_NONE, NULL, &_inner_error0_);
#line 136 "../src/window.vala"
		file_stream = _tmp10_;
#line 136 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 136 "../src/window.vala"
			_g_object_unref0 (file);
#line 136 "../src/window.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 136 "../src/window.vala"
			g_clear_error (&_inner_error0_);
#line 136 "../src/window.vala"
			return;
#line 818 "window.c"
		}
#line 133 "../src/window.vala"
		_g_object_unref0 (file_stream);
#line 822 "window.c"
	} else {
		GFile* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
#line 139 "../src/window.vala"
		_tmp11_ = file;
#line 139 "../src/window.vala"
		_tmp12_ = g_file_get_path (_tmp11_);
#line 139 "../src/window.vala"
		_tmp13_ = _tmp12_;
#line 139 "../src/window.vala"
		g_print ("File %s created", _tmp13_);
#line 139 "../src/window.vala"
		_g_free0 (_tmp13_);
#line 837 "window.c"
	}
#line 143 "../src/window.vala"
	_tmp14_ = json_parser_new ();
#line 143 "../src/window.vala"
	parser = _tmp14_;
#line 144 "../src/window.vala"
	_tmp15_ = parser;
#line 144 "../src/window.vala"
	_tmp16_ = file;
#line 144 "../src/window.vala"
	_tmp17_ = g_file_get_path (_tmp16_);
#line 144 "../src/window.vala"
	_tmp18_ = _tmp17_;
#line 144 "../src/window.vala"
	json_parser_load_from_file (_tmp15_, _tmp18_, &_inner_error0_);
#line 144 "../src/window.vala"
	_g_free0 (_tmp18_);
#line 144 "../src/window.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 144 "../src/window.vala"
		_g_object_unref0 (parser);
#line 144 "../src/window.vala"
		_g_object_unref0 (file);
#line 144 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 144 "../src/window.vala"
		g_clear_error (&_inner_error0_);
#line 144 "../src/window.vala"
		return;
#line 867 "window.c"
	}
#line 145 "../src/window.vala"
	_tmp19_ = parser;
#line 145 "../src/window.vala"
	_tmp20_ = json_parser_get_root (_tmp19_);
#line 145 "../src/window.vala"
	_tmp21_ = json_node_get_object (_tmp20_);
#line 145 "../src/window.vala"
	_tmp22_ = _json_object_ref0 (_tmp21_);
#line 145 "../src/window.vala"
	root_object = _tmp22_;
#line 146 "../src/window.vala"
	_tmp23_ = root_object;
#line 146 "../src/window.vala"
	_tmp24_ = json_object_get_array_member (_tmp23_, "Tasks");
#line 146 "../src/window.vala"
	_tmp25_ = _json_array_ref0 (_tmp24_);
#line 146 "../src/window.vala"
	array = _tmp25_;
#line 148 "../src/window.vala"
	_tmp26_ = array;
#line 148 "../src/window.vala"
	_tmp27_ = json_array_get_elements (_tmp26_);
#line 891 "window.c"
	{
		GList* tasks_collection = NULL;
		GList* tasks_it = NULL;
#line 148 "../src/window.vala"
		tasks_collection = _tmp27_;
#line 148 "../src/window.vala"
		for (tasks_it = tasks_collection; tasks_it != NULL; tasks_it = tasks_it->next) {
#line 899 "window.c"
			JsonNode* tasks = NULL;
#line 148 "../src/window.vala"
			tasks = (JsonNode*) tasks_it->data;
#line 903 "window.c"
			{
				JsonObject* obj = NULL;
				JsonNode* _tmp28_;
				JsonObject* _tmp29_;
				JsonObject* _tmp30_;
				JsonObject* _tmp31_;
				GList* _tmp32_;
				HacerActionAgendaRow* item_row = NULL;
				const gchar* _tmp41_;
				GtkListBox* _tmp42_;
				HacerActionAgendaRow* _tmp43_;
				GtkListBox* _tmp44_;
				HacerActionAgendaRow* _tmp45_;
#line 149 "../src/window.vala"
				_tmp28_ = tasks;
#line 149 "../src/window.vala"
				_tmp29_ = json_node_get_object (_tmp28_);
#line 149 "../src/window.vala"
				_tmp30_ = _json_object_ref0 (_tmp29_);
#line 149 "../src/window.vala"
				obj = _tmp30_;
#line 150 "../src/window.vala"
				_tmp31_ = obj;
#line 150 "../src/window.vala"
				_tmp32_ = json_object_get_members (_tmp31_);
#line 929 "window.c"
				{
					GList* members_collection = NULL;
					GList* members_it = NULL;
#line 150 "../src/window.vala"
					members_collection = _tmp32_;
#line 150 "../src/window.vala"
					for (members_it = members_collection; members_it != NULL; members_it = members_it->next) {
#line 937 "window.c"
						const gchar* members = NULL;
#line 150 "../src/window.vala"
						members = (const gchar*) members_it->data;
#line 941 "window.c"
						{
							const gchar* _tmp33_;
							const gchar* _tmp34_;
							GQuark _tmp36_ = 0U;
#line 151 "../src/window.vala"
							static GQuark _tmp35_label0 = 0;
#line 151 "../src/window.vala"
							static GQuark _tmp35_label1 = 0;
#line 151 "../src/window.vala"
							static GQuark _tmp35_label2 = 0;
#line 151 "../src/window.vala"
							_tmp33_ = members;
#line 151 "../src/window.vala"
							_tmp34_ = _tmp33_;
#line 151 "../src/window.vala"
							_tmp36_ = (NULL == _tmp34_) ? 0 : g_quark_from_string (_tmp34_);
#line 151 "../src/window.vala"
							if (_tmp36_ == ((0 != _tmp35_label0) ? _tmp35_label0 : (_tmp35_label0 = g_quark_from_static_string ("task_name")))) {
#line 151 "../src/window.vala"
								switch (0) {
#line 962 "window.c"
									default:
									{
										JsonObject* _tmp37_;
										const gchar* _tmp38_;
#line 153 "../src/window.vala"
										_tmp37_ = obj;
#line 153 "../src/window.vala"
										_tmp38_ = json_object_get_string_member (_tmp37_, "task_name");
#line 153 "../src/window.vala"
										task_name = _tmp38_;
#line 154 "../src/window.vala"
										break;
#line 975 "window.c"
									}
								}
							} else if (_tmp36_ == ((0 != _tmp35_label1) ? _tmp35_label1 : (_tmp35_label1 = g_quark_from_static_string ("complete")))) {
#line 151 "../src/window.vala"
								switch (0) {
#line 981 "window.c"
									default:
									{
										JsonObject* _tmp39_;
#line 156 "../src/window.vala"
										_tmp39_ = obj;
#line 156 "../src/window.vala"
										complete = json_object_get_boolean_member (_tmp39_, "complete");
#line 157 "../src/window.vala"
										break;
#line 991 "window.c"
									}
								}
							} else if (_tmp36_ == ((0 != _tmp35_label2) ? _tmp35_label2 : (_tmp35_label2 = g_quark_from_static_string ("starred")))) {
#line 151 "../src/window.vala"
								switch (0) {
#line 997 "window.c"
									default:
									{
										JsonObject* _tmp40_;
#line 159 "../src/window.vala"
										_tmp40_ = obj;
#line 159 "../src/window.vala"
										starred = json_object_get_boolean_member (_tmp40_, "starred");
#line 160 "../src/window.vala"
										break;
#line 1007 "window.c"
									}
								}
							}
						}
					}
#line 150 "../src/window.vala"
					(members_collection == NULL) ? NULL : (members_collection = (g_list_free (members_collection), NULL));
#line 1015 "window.c"
				}
#line 164 "../src/window.vala"
				_tmp41_ = task_name;
#line 164 "../src/window.vala"
				_tmp42_ = self->priv->task_list;
#line 164 "../src/window.vala"
				_tmp43_ = hacer_action_agenda_row_new (_tmp41_, complete, starred, _tmp42_);
#line 164 "../src/window.vala"
				g_object_ref_sink (_tmp43_);
#line 164 "../src/window.vala"
				item_row = _tmp43_;
#line 165 "../src/window.vala"
				_tmp44_ = self->priv->task_list;
#line 165 "../src/window.vala"
				_tmp45_ = item_row;
#line 165 "../src/window.vala"
				gtk_list_box_append (_tmp44_, (GtkWidget*) _tmp45_);
#line 148 "../src/window.vala"
				_g_object_unref0 (item_row);
#line 148 "../src/window.vala"
				_json_object_unref0 (obj);
#line 1037 "window.c"
			}
		}
#line 148 "../src/window.vala"
		(tasks_collection == NULL) ? NULL : (tasks_collection = (g_list_free (tasks_collection), NULL));
#line 1042 "window.c"
	}
#line 125 "../src/window.vala"
	_json_array_unref0 (array);
#line 125 "../src/window.vala"
	_json_object_unref0 (root_object);
#line 125 "../src/window.vala"
	_g_object_unref0 (parser);
#line 125 "../src/window.vala"
	_g_object_unref0 (file);
#line 1052 "window.c"
}

static void
hacer_window_class_init (HacerWindowClass * klass,
                         gpointer klass_data)
{
#line 24 "../src/window.vala"
	hacer_window_parent_class = g_type_class_peek_parent (klass);
#line 24 "../src/window.vala"
	g_type_class_adjust_private_offset (klass, &HacerWindow_private_offset);
#line 24 "../src/window.vala"
	G_OBJECT_CLASS (klass)->finalize = hacer_window_finalize;
#line 24 "../src/window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/com/github/halfmexican/hacer/window.ui");
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "task_entry", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, task_entry));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "task_list", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, task_list));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "leaflet_forward", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, leaflet_forward));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "leaflet_back", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, leaflet_back));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "task_view", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, task_view));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "list_view", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, list_view));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "list_box_list", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, list_box_list));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "adw_leaflet", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, adw_leaflet));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "all_tasks_row", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, all_tasks_row));
#line 1085 "window.c"
}

static void
hacer_window_instance_init (HacerWindow * self,
                            gpointer klass)
{
#line 24 "../src/window.vala"
	self->priv = hacer_window_get_instance_private (self);
#line 24 "../src/window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 1096 "window.c"
}

static void
hacer_window_finalize (GObject * obj)
{
	HacerWindow * self;
#line 24 "../src/window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HACER_TYPE_WINDOW, HacerWindow);
#line 24 "../src/window.vala"
	G_OBJECT_CLASS (hacer_window_parent_class)->finalize (obj);
#line 1107 "window.c"
}

static GType
hacer_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (HacerWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hacer_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HacerWindow), 0, (GInstanceInitFunc) hacer_window_instance_init, NULL };
	GType hacer_window_type_id;
	hacer_window_type_id = g_type_register_static (adw_application_window_get_type (), "HacerWindow", &g_define_type_info, 0);
	HacerWindow_private_offset = g_type_add_instance_private (hacer_window_type_id, sizeof (HacerWindowPrivate));
	return hacer_window_type_id;
}

GType
hacer_window_get_type (void)
{
	static volatile gsize hacer_window_type_id__once = 0;
	if (g_once_init_enter (&hacer_window_type_id__once)) {
		GType hacer_window_type_id;
		hacer_window_type_id = hacer_window_get_type_once ();
		g_once_init_leave (&hacer_window_type_id__once, hacer_window_type_id);
	}
	return hacer_window_type_id__once;
}

