/* window.c generated by valac 0.56.3, the Vala compiler
 * generated from window.vala, do not modify */

/* window.vala
 *
 * Copyright 2022 Jose Hunter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <json-glib/json-glib.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define HACER_TYPE_WINDOW (hacer_window_get_type ())
#define HACER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HACER_TYPE_WINDOW, HacerWindow))
#define HACER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HACER_TYPE_WINDOW, HacerWindowClass))
#define HACER_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HACER_TYPE_WINDOW))
#define HACER_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HACER_TYPE_WINDOW))
#define HACER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HACER_TYPE_WINDOW, HacerWindowClass))

typedef struct _HacerWindow HacerWindow;
typedef struct _HacerWindowClass HacerWindowClass;
typedef struct _HacerWindowPrivate HacerWindowPrivate;
enum  {
	HACER_WINDOW_0_PROPERTY,
	HACER_WINDOW_NUM_PROPERTIES
};
static GParamSpec* hacer_window_properties[HACER_WINDOW_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define HACER_TYPE_ACTION_AGENDA_ROW (hacer_action_agenda_row_get_type ())
#define HACER_ACTION_AGENDA_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HACER_TYPE_ACTION_AGENDA_ROW, HacerActionAgendaRow))
#define HACER_ACTION_AGENDA_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HACER_TYPE_ACTION_AGENDA_ROW, HacerActionAgendaRowClass))
#define HACER_IS_ACTION_AGENDA_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HACER_TYPE_ACTION_AGENDA_ROW))
#define HACER_IS_ACTION_AGENDA_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HACER_TYPE_ACTION_AGENDA_ROW))
#define HACER_ACTION_AGENDA_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HACER_TYPE_ACTION_AGENDA_ROW, HacerActionAgendaRowClass))

typedef struct _HacerActionAgendaRow HacerActionAgendaRow;
typedef struct _HacerActionAgendaRowClass HacerActionAgendaRowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _HacerWindow {
	AdwApplicationWindow parent_instance;
	HacerWindowPrivate * priv;
};

struct _HacerWindowClass {
	AdwApplicationWindowClass parent_class;
};

struct _HacerWindowPrivate {
	GtkEntry* task_entry;
	GtkListBox* task_list;
	GtkButton* leaflet_forward;
	GtkButton* leaflet_back;
	GtkBox* task_view;
	GtkBox* list_view;
	GtkListBox* list_box_list;
	AdwLeaflet* adw_leaflet;
	AdwActionRow* all_tasks_row;
	AdwActionRow* completed_tasks_row;
	AdwActionRow* starred_tasks_row;
};

static gint HacerWindow_private_offset;
static gpointer hacer_window_parent_class = NULL;

VALA_EXTERN GType hacer_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HacerWindow, g_object_unref)
VALA_EXTERN HacerWindow* hacer_window_new (GtkApplication* app);
VALA_EXTERN HacerWindow* hacer_window_construct (GType object_type,
                                     GtkApplication* app);
VALA_EXTERN void hacer_window_on_enter_released (HacerWindow* self);
static void _hacer_window_on_enter_released_gtk_entry_activate (GtkEntry* _sender,
                                                         gpointer self);
VALA_EXTERN void hacer_window_show_task_view (HacerWindow* self);
static void _hacer_window_show_task_view_gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self);
VALA_EXTERN void hacer_window_show_list_view (HacerWindow* self);
static void _hacer_window_show_list_view_gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self);
VALA_EXTERN void hacer_window_show_all_tasks (HacerWindow* self);
static void _hacer_window_show_all_tasks_adw_action_row_activated (AdwActionRow* _sender,
                                                            gpointer self);
static void _hacer_window_entry_add (HacerWindow* self,
                              const gchar* task_name);
VALA_EXTERN void hacer_window_load_task_from_json (HacerWindow* self);
VALA_EXTERN GType hacer_action_agenda_row_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HacerActionAgendaRow, g_object_unref)
VALA_EXTERN HacerActionAgendaRow* hacer_action_agenda_row_new (const gchar* task_name,
                                                   gboolean completed,
                                                   gboolean starred,
                                                   GtkListBox* parent_list_box);
VALA_EXTERN HacerActionAgendaRow* hacer_action_agenda_row_construct (GType object_type,
                                                         const gchar* task_name,
                                                         gboolean completed,
                                                         gboolean starred,
                                                         GtkListBox* parent_list_box);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static void _vala_JsonNode_free (JsonNode* self);
static void hacer_window_finalize (GObject * obj);
static GType hacer_window_get_type_once (void);

static inline gpointer
hacer_window_get_instance_private (HacerWindow* self)
{
	return G_STRUCT_MEMBER_P (self, HacerWindow_private_offset);
}

static void
_hacer_window_on_enter_released_gtk_entry_activate (GtkEntry* _sender,
                                                    gpointer self)
{
#line 45 "../src/window.vala"
	hacer_window_on_enter_released ((HacerWindow*) self);
#line 148 "window.c"
}

static void
_hacer_window_show_task_view_gtk_button_clicked (GtkButton* _sender,
                                                 gpointer self)
{
#line 46 "../src/window.vala"
	hacer_window_show_task_view ((HacerWindow*) self);
#line 157 "window.c"
}

static void
_hacer_window_show_list_view_gtk_button_clicked (GtkButton* _sender,
                                                 gpointer self)
{
#line 47 "../src/window.vala"
	hacer_window_show_list_view ((HacerWindow*) self);
#line 166 "window.c"
}

static void
_hacer_window_show_all_tasks_adw_action_row_activated (AdwActionRow* _sender,
                                                       gpointer self)
{
#line 48 "../src/window.vala"
	hacer_window_show_all_tasks ((HacerWindow*) self);
#line 175 "window.c"
}

HacerWindow*
hacer_window_construct (GType object_type,
                        GtkApplication* app)
{
	HacerWindow * self = NULL;
	GtkEntry* _tmp0_;
	GtkButton* _tmp1_;
	GtkButton* _tmp2_;
	AdwActionRow* _tmp3_;
	AdwLeaflet* _tmp4_;
	GtkBox* _tmp5_;
	GtkListBox* _tmp6_;
	GtkListBox* _tmp7_;
	GtkListBoxRow* _tmp8_;
#line 40 "../src/window.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 41 "../src/window.vala"
	self = (HacerWindow*) g_object_new (object_type, "application", app, NULL);
#line 42 "../src/window.vala"
	gtk_window_set_icon_name ((GtkWindow*) self, "com.github.halfmexican.hacer");
#line 45 "../src/window.vala"
	_tmp0_ = self->priv->task_entry;
#line 45 "../src/window.vala"
	g_signal_connect_object (_tmp0_, "activate", (GCallback) _hacer_window_on_enter_released_gtk_entry_activate, self, 0);
#line 46 "../src/window.vala"
	_tmp1_ = self->priv->leaflet_forward;
#line 46 "../src/window.vala"
	g_signal_connect_object (_tmp1_, "clicked", (GCallback) _hacer_window_show_task_view_gtk_button_clicked, self, 0);
#line 47 "../src/window.vala"
	_tmp2_ = self->priv->leaflet_back;
#line 47 "../src/window.vala"
	g_signal_connect_object (_tmp2_, "clicked", (GCallback) _hacer_window_show_list_view_gtk_button_clicked, self, 0);
#line 48 "../src/window.vala"
	_tmp3_ = self->priv->all_tasks_row;
#line 48 "../src/window.vala"
	g_signal_connect_object (_tmp3_, "activated", (GCallback) _hacer_window_show_all_tasks_adw_action_row_activated, self, 0);
#line 51 "../src/window.vala"
	_tmp4_ = self->priv->adw_leaflet;
#line 51 "../src/window.vala"
	_tmp5_ = self->priv->task_view;
#line 51 "../src/window.vala"
	adw_leaflet_set_visible_child (_tmp4_, (GtkWidget*) _tmp5_);
#line 52 "../src/window.vala"
	_tmp6_ = self->priv->list_box_list;
#line 52 "../src/window.vala"
	_tmp7_ = self->priv->list_box_list;
#line 52 "../src/window.vala"
	_tmp8_ = gtk_list_box_get_row_at_index (_tmp7_, 0);
#line 52 "../src/window.vala"
	gtk_list_box_select_row (_tmp6_, _tmp8_);
#line 40 "../src/window.vala"
	return self;
#line 230 "window.c"
}

HacerWindow*
hacer_window_new (GtkApplication* app)
{
#line 40 "../src/window.vala"
	return hacer_window_construct (HACER_TYPE_WINDOW, app);
#line 238 "window.c"
}

void
hacer_window_on_enter_released (HacerWindow* self)
{
	gchar* text = NULL;
	GtkEntry* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
#line 55 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 56 "../src/window.vala"
	_tmp0_ = self->priv->task_entry;
#line 56 "../src/window.vala"
	_tmp1_ = gtk_editable_get_text ((GtkEditable*) _tmp0_);
#line 56 "../src/window.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 56 "../src/window.vala"
	text = _tmp2_;
#line 57 "../src/window.vala"
	_hacer_window_entry_add (self, text);
#line 55 "../src/window.vala"
	_g_free0 (text);
#line 262 "window.c"
}

void
hacer_window_show_task_view (HacerWindow* self)
{
	AdwLeaflet* _tmp0_;
	GtkBox* _tmp1_;
#line 60 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 61 "../src/window.vala"
	_tmp0_ = self->priv->adw_leaflet;
#line 61 "../src/window.vala"
	_tmp1_ = self->priv->task_view;
#line 61 "../src/window.vala"
	adw_leaflet_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 278 "window.c"
}

void
hacer_window_show_list_view (HacerWindow* self)
{
	AdwLeaflet* _tmp0_;
	GtkBox* _tmp1_;
#line 64 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 65 "../src/window.vala"
	_tmp0_ = self->priv->adw_leaflet;
#line 65 "../src/window.vala"
	_tmp1_ = self->priv->list_view;
#line 65 "../src/window.vala"
	adw_leaflet_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 294 "window.c"
}

void
hacer_window_show_all_tasks (HacerWindow* self)
{
#line 68 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 70 "../src/window.vala"
	hacer_window_load_task_from_json (self);
#line 304 "window.c"
}

static void
_hacer_window_entry_add (HacerWindow* self,
                         const gchar* task_name)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	HacerActionAgendaRow* item_row = NULL;
	GtkListBox* _tmp4_;
	HacerActionAgendaRow* _tmp5_;
	GtkListBox* _tmp6_;
	GtkEntry* _tmp7_;
#line 73 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 73 "../src/window.vala"
	g_return_if_fail (task_name != NULL);
#line 74 "../src/window.vala"
	_tmp0_ = g_strconcat ("New Task: ", task_name, NULL);
#line 74 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 74 "../src/window.vala"
	_tmp2_ = g_strconcat (_tmp1_, "\n", NULL);
#line 74 "../src/window.vala"
	_tmp3_ = _tmp2_;
#line 74 "../src/window.vala"
	g_print ("%s", _tmp3_);
#line 74 "../src/window.vala"
	_g_free0 (_tmp3_);
#line 74 "../src/window.vala"
	_g_free0 (_tmp1_);
#line 75 "../src/window.vala"
	_tmp4_ = self->priv->task_list;
#line 75 "../src/window.vala"
	_tmp5_ = hacer_action_agenda_row_new (task_name, FALSE, FALSE, _tmp4_);
#line 75 "../src/window.vala"
	g_object_ref_sink (_tmp5_);
#line 75 "../src/window.vala"
	item_row = _tmp5_;
#line 76 "../src/window.vala"
	_tmp6_ = self->priv->task_list;
#line 76 "../src/window.vala"
	gtk_list_box_append (_tmp6_, (GtkWidget*) item_row);
#line 77 "../src/window.vala"
	_tmp7_ = self->priv->task_entry;
#line 77 "../src/window.vala"
	gtk_editable_set_text ((GtkEditable*) _tmp7_, "");
#line 73 "../src/window.vala"
	_g_object_unref0 (item_row);
#line 356 "window.c"
}

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
#line 94 "../src/window.vala"
	return g_boxed_copy (json_node_get_type (), self);
#line 364 "window.c"
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
#line 94 "../src/window.vala"
	return self ? _vala_JsonNode_copy (self) : NULL;
#line 372 "window.c"
}

static void
_vala_JsonNode_free (JsonNode* self)
{
#line 88 "../src/window.vala"
	g_boxed_free (json_node_get_type (), self);
#line 380 "window.c"
}

void
hacer_window_load_task_from_json (HacerWindow* self)
{
	GFile* file = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GFile* _tmp3_;
	GFile* _tmp4_;
	const gchar* task = NULL;
	GFile* _tmp5_;
	GError* _inner_error0_ = NULL;
#line 80 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 81 "../src/window.vala"
	_tmp0_ = g_get_user_data_dir ();
#line 81 "../src/window.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/tasks.json", NULL);
#line 81 "../src/window.vala"
	_tmp2_ = _tmp1_;
#line 81 "../src/window.vala"
	_tmp3_ = g_file_new_for_path (_tmp2_);
#line 81 "../src/window.vala"
	_tmp4_ = _tmp3_;
#line 81 "../src/window.vala"
	_g_free0 (_tmp2_);
#line 81 "../src/window.vala"
	file = _tmp4_;
#line 82 "../src/window.vala"
	task = NULL;
#line 84 "../src/window.vala"
	_tmp5_ = file;
#line 84 "../src/window.vala"
	if (!g_file_query_exists (_tmp5_, NULL)) {
#line 417 "window.c"
		GFile* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
#line 85 "../src/window.vala"
		_tmp6_ = file;
#line 85 "../src/window.vala"
		_tmp7_ = g_file_get_path (_tmp6_);
#line 85 "../src/window.vala"
		_tmp8_ = _tmp7_;
#line 85 "../src/window.vala"
		g_print ("File '%s' does not exist.", _tmp8_);
#line 85 "../src/window.vala"
		_g_free0 (_tmp8_);
#line 431 "window.c"
	}
	{
		JsonParser* parser = NULL;
		JsonParser* _tmp9_;
		GFileInputStream* stream = NULL;
		GFile* _tmp10_;
		GFileInputStream* _tmp11_;
		JsonParser* _tmp12_;
		GFileInputStream* _tmp13_;
		JsonNode* node = NULL;
		JsonParser* _tmp14_;
		JsonNode* _tmp15_;
		JsonNode* _tmp16_;
		JsonReader* reader = NULL;
		JsonReader* _tmp17_;
		gchar* _tmp18_;
#line 90 "../src/window.vala"
		_tmp9_ = json_parser_new ();
#line 90 "../src/window.vala"
		parser = _tmp9_;
#line 91 "../src/window.vala"
		_tmp10_ = file;
#line 91 "../src/window.vala"
		_tmp11_ = g_file_read (_tmp10_, NULL, &_inner_error0_);
#line 91 "../src/window.vala"
		stream = _tmp11_;
#line 91 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 91 "../src/window.vala"
			_g_object_unref0 (parser);
#line 462 "window.c"
			goto __catch0_g_error;
		}
#line 93 "../src/window.vala"
		_tmp12_ = parser;
#line 93 "../src/window.vala"
		_tmp13_ = stream;
#line 93 "../src/window.vala"
		json_parser_load_from_stream (_tmp12_, (GInputStream*) _tmp13_, NULL, &_inner_error0_);
#line 93 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 93 "../src/window.vala"
			_g_object_unref0 (stream);
#line 93 "../src/window.vala"
			_g_object_unref0 (parser);
#line 477 "window.c"
			goto __catch0_g_error;
		}
#line 94 "../src/window.vala"
		_tmp14_ = parser;
#line 94 "../src/window.vala"
		_tmp15_ = json_parser_get_root (_tmp14_);
#line 94 "../src/window.vala"
		_tmp16_ = __vala_JsonNode_copy0 (_tmp15_);
#line 94 "../src/window.vala"
		node = _tmp16_;
#line 95 "../src/window.vala"
		_tmp17_ = json_reader_new (node);
#line 95 "../src/window.vala"
		reader = _tmp17_;
#line 96 "../src/window.vala"
		_tmp18_ = (gchar*) json_reader_count_elements (reader);
#line 96 "../src/window.vala"
		g_print ("%s", _tmp18_);
#line 96 "../src/window.vala"
		_g_free0 (_tmp18_);
#line 88 "../src/window.vala"
		_g_object_unref0 (reader);
#line 88 "../src/window.vala"
		__vala_JsonNode_free0 (node);
#line 88 "../src/window.vala"
		_g_object_unref0 (stream);
#line 88 "../src/window.vala"
		_g_object_unref0 (parser);
#line 506 "window.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp19_;
#line 88 "../src/window.vala"
		e = _inner_error0_;
#line 88 "../src/window.vala"
		_inner_error0_ = NULL;
#line 101 "../src/window.vala"
		_tmp19_ = e->message;
#line 101 "../src/window.vala"
		g_error ("window.vala:101: %s", _tmp19_);
#line 88 "../src/window.vala"
		_g_error_free0 (e);
#line 523 "window.c"
	}
	__finally0:
#line 88 "../src/window.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 88 "../src/window.vala"
		_g_object_unref0 (file);
#line 88 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 88 "../src/window.vala"
		g_clear_error (&_inner_error0_);
#line 88 "../src/window.vala"
		return;
#line 536 "window.c"
	}
#line 80 "../src/window.vala"
	_g_object_unref0 (file);
#line 540 "window.c"
}

static void
hacer_window_class_init (HacerWindowClass * klass,
                         gpointer klass_data)
{
#line 24 "../src/window.vala"
	hacer_window_parent_class = g_type_class_peek_parent (klass);
#line 24 "../src/window.vala"
	g_type_class_adjust_private_offset (klass, &HacerWindow_private_offset);
#line 24 "../src/window.vala"
	G_OBJECT_CLASS (klass)->finalize = hacer_window_finalize;
#line 24 "../src/window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/com/github/halfmexican/hacer/window.ui");
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "task_entry", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, task_entry));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "task_list", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, task_list));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "leaflet_forward", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, leaflet_forward));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "leaflet_back", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, leaflet_back));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "task_view", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, task_view));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "list_view", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, list_view));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "list_box_list", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, list_box_list));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "adw_leaflet", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, adw_leaflet));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "all_tasks_row", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, all_tasks_row));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "completed_tasks_row", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, completed_tasks_row));
#line 24 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "starred_tasks_row", FALSE, HacerWindow_private_offset + G_STRUCT_OFFSET (HacerWindowPrivate, starred_tasks_row));
#line 577 "window.c"
}

static void
hacer_window_instance_init (HacerWindow * self,
                            gpointer klass)
{
#line 24 "../src/window.vala"
	self->priv = hacer_window_get_instance_private (self);
#line 24 "../src/window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 588 "window.c"
}

static void
hacer_window_finalize (GObject * obj)
{
	HacerWindow * self;
#line 24 "../src/window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HACER_TYPE_WINDOW, HacerWindow);
#line 24 "../src/window.vala"
	G_OBJECT_CLASS (hacer_window_parent_class)->finalize (obj);
#line 599 "window.c"
}

static GType
hacer_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (HacerWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hacer_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HacerWindow), 0, (GInstanceInitFunc) hacer_window_instance_init, NULL };
	GType hacer_window_type_id;
	hacer_window_type_id = g_type_register_static (adw_application_window_get_type (), "HacerWindow", &g_define_type_info, 0);
	HacerWindow_private_offset = g_type_add_instance_private (hacer_window_type_id, sizeof (HacerWindowPrivate));
	return hacer_window_type_id;
}

GType
hacer_window_get_type (void)
{
	static volatile gsize hacer_window_type_id__once = 0;
	if (g_once_init_enter (&hacer_window_type_id__once)) {
		GType hacer_window_type_id;
		hacer_window_type_id = hacer_window_get_type_once ();
		g_once_init_leave (&hacer_window_type_id__once, hacer_window_type_id);
	}
	return hacer_window_type_id__once;
}

